// <auto-generated />
namespace DeadLiner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class taskManage1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taskManage1));
        
        string IMigrationMetadata.Id
        {
            get { return "201708091109476_taskManage1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
